version: "3"
services:
 web:
  image: nginx:stable
  volumes:
   - ./mysite.template:/etc/nginx/conf.d/mysite.template:ro
   - ./nginx.conf:/etc/nginx/nginx.conf:ro
   - ./fastcgi_params:/etc/nginx/fastcgi_params:ro
   - ~/app/DOCKER_WEB_APP:/var/www/html/
  ports:
   - DOCKER_WEB_PORT:80
  environment:
   - NGINX_HOST=test.com
   - NGINX_PORT=80
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  links:
   - php-fpm
 php-fpm:
  image: jingyuan4ever/php
  volumes:
   - ~/app/DOCKER_WEB_APP:/var/www/html/
   - ./php.ini:/usr/local/etc/php/conf.d/php.ini
  external_links:
   - db_db_1
networks:
  default:
    external:
      name: db_default
