version: "3"
services:
 php-fpm:
  image: jingyuan4ever/php
  volumes:
   - /root/app/wordpress:/var/www/html/
   - ./php.ini:/usr/local/etc/php/conf.d/php.ini
  links:
   - db
 db:
  image: mysql:5.7
  environment:
   - MYSQL_ROOT_PASSWORD=123456
