version: "3"
services:
 web:
  image: nginx:stable
  volumes:
   - ./mysite.template:/etc/nginx/conf.d/mysite.template:ro
   - ./fastcgi_params:/etc/nginx/fastcgi_params:ro
   - ~/app:/var/www/html/
  ports:
   - 80:80
  environment:
   - NGINX_HOST=test.com
   - NGINX_PORT=80
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  links:
   - php-fpm
 php-fpm:
  image: jingyuan4ever/php
  volumes:
   - ~/app:/var/www/html/
   - ./php.ini:/usr/local/etc/php/conf.d/php.ini
  links:
   - db
 db:
  image: mysql:5.7
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=123456
